# Generated by Django 5.2.7 on 2026-02-05 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_am',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_om',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_am',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_om',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
