# Generated by Django 5.2.7 on 2026-02-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_article_content_am_article_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='kebele',
            field=models.CharField(blank=True, choices=[('Bosa Addis', 'Bosa Addis'), ('Bosa Kitto', 'Bosa Kitto'), ('Ginjo', 'Ginjo'), ('Ginjo Guduru', 'Ginjo Guduru'), ('Hermata', 'Hermata'), ('Hermata Merkato', 'Hermata Merkato'), ('Jiren', 'Jiren'), ('Kofe', 'Kofe'), ('Mendera Kochi', 'Mendera Kochi'), ('Seto Semero', 'Seto Semero')], max_length=100),
        ),
    ]
